"""
Writing the WBSO hours report to a .xlsx workbook.

Layout follows the usual spreadsheet discipline: one flat sheet of raw
per-ticket hours as the single source of truth, and every aggregate above it
expressed as a formula referencing that sheet. Open the file, change a number
on Detail, and the epic subtotals, engineer totals and WBSO shares all follow.

  Assumptions        parameters the run used, incl. the hours-per-day constant
                     that the Summary formulas reference
  Detail             one row per engineer / epic / ticket — the input data
  By Engineer & Epic hours per (engineer, epic), via SUMIFS over Detail
  Summary            hours, capacity and WBSO share per engineer
  Diagnostics        epics that need attention in the mapping CSV
"""

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

FONT = "Arial"
HEADER_FILL = PatternFill("solid", fgColor="1F3864")
HEADER_FONT = Font(name=FONT, bold=True, color="FFFFFF", size=11)
TITLE_FONT = Font(name=FONT, bold=True, size=14)
BODY_FONT = Font(name=FONT, size=10)
BOLD_FONT = Font(name=FONT, bold=True, size=10)
INPUT_FONT = Font(name=FONT, size=10, color="0000FF")  # blue = hardcoded input
NOTE_FONT = Font(name=FONT, size=9, italic=True, color="666666")
ASSUMPTION_FILL = PatternFill("solid", fgColor="FFFF00")
SUBTOTAL_FILL = PatternFill("solid", fgColor="DDEBF7")
THIN = Side(style="thin", color="BFBFBF")
BOX = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

HOURS_FMT = "0.0"
PCT_FMT = "0.0%"

# Assumptions!B5 holds hours-per-day; Summary formulas reference it.
HOURS_PER_DAY_REF = "Assumptions!$B$5"


def _write_header(ws, row, headers, widths=None):
    for col, title in enumerate(headers, 1):
        cell = ws.cell(row=row, column=col, value=title)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = BOX
    if widths:
        for col, width in enumerate(widths, 1):
            ws.column_dimensions[get_column_letter(col)].width = width
    ws.freeze_panes = ws.cell(row=row + 1, column=1)


def _flatten(totals, epic_of, summaries):
    """
    totals[engineer][epic_label][ticket] -> hours, into flat sorted rows.
    Sorting happens here in Python: LibreOffice cannot evaluate SORT().
    """
    rows = []
    for engineer, epic_map in totals.items():
        for epic_label, tickets in epic_map.items():
            for ticket, hours in tickets.items():
                epic_key = (epic_of.get(ticket) or (None, epic_label))[0] or ""
                rows.append({
                    "engineer": engineer,
                    "epic_key": epic_key,
                    "epic_label": epic_label,
                    "ticket": ticket,
                    "summary": summaries.get(ticket, ""),
                    "hours": hours,
                })
    engineer_totals = {}
    for r in rows:
        engineer_totals[r["engineer"]] = engineer_totals.get(r["engineer"], 0) + r["hours"]
    rows.sort(key=lambda r: (-engineer_totals[r["engineer"]], r["engineer"],
                             r["epic_key"], -r["hours"], r["ticket"]))
    return rows


def _sheet_assumptions(wb, meta, diagnostics):
    ws = wb.create_sheet("Assumptions")
    ws["A1"] = "Consolidated WBSO Hours — run parameters"
    ws["A1"].font = TITLE_FONT
    ws.column_dimensions["A"].width = 34
    ws.column_dimensions["B"].width = 46

    ws["A3"] = "Parameter"
    ws["B3"] = "Value"
    for c in ("A3", "B3"):
        ws[c].font = HEADER_FONT
        ws[c].fill = HEADER_FILL
        ws[c].border = BOX

    # Row 5 is referenced by the Summary formulas — keep it at this address.
    entries = [
        ("Hours per engineer per day", meta["hours_per_day"]),
        ("Reporting month", meta["month"]),
        ("Team", meta["team"]),
        ("Jira project", meta["project"]),
        ("Jira board", meta["board_id"]),
        ("Epic filter", meta["filter_scope"]),
        ("WBSO epics in scope", meta["wbso_epic_count"]),
        ("Mapping CSV", meta["mapping_file"]),
        ("Generated by", "engineering-metrics / consolidated-wbso-hours"),
    ]
    row = 5
    for label, value in entries:
        ws.cell(row=row, column=1, value=label).font = BOLD_FONT
        cell = ws.cell(row=row, column=2, value=value)
        cell.font = INPUT_FONT
        if row == 5:
            cell.fill = ASSUMPTION_FILL
            cell.number_format = HOURS_FMT
        row += 1

    row += 1
    ws.cell(row=row, column=1, value="Method").font = BOLD_FONT
    notes = [
        "A weekday on which an engineer held a ticket while it was In Progress "
        "makes that ticket active for them that day.",
        "Each engineer-day is worth at most the hours-per-day figure above, split "
        "equally across every ticket active that day.",
        "The split denominator is ALL tickets held that day, including non-WBSO "
        "ones. Filtering to WBSO removes rows but never inflates the hours "
        "remaining — important for a subsidy claim.",
        "Weekends are excluded. Public holidays are NOT excluded.",
        "Hours on the Detail sheet are computed by the tool from the Jira "
        "changelog; they are inputs here, not sheet-derived. Every total above "
        "them is a formula.",
    ]
    for note in notes:
        row += 1
        cell = ws.cell(row=row, column=1, value="• " + note)
        cell.font = NOTE_FONT
        cell.alignment = Alignment(wrap_text=True, vertical="top")
        ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=2)
        ws.row_dimensions[row].height = 28
    return ws


def _sheet_detail(wb, rows):
    ws = wb.create_sheet("Detail")
    ws["A1"] = "Per-ticket WBSO hours (input data from Jira)"
    ws["A1"].font = TITLE_FONT
    _write_header(
        ws, 3,
        ["Engineer", "Epic key", "Epic", "Ticket", "Ticket summary", "Hours"],
        [24, 12, 34, 14, 50, 10],
    )

    row = 4
    for r in rows:
        ws.cell(row=row, column=1, value=r["engineer"]).font = BODY_FONT
        ws.cell(row=row, column=2, value=r["epic_key"]).font = BODY_FONT
        ws.cell(row=row, column=3, value=r["epic_label"]).font = BODY_FONT
        ws.cell(row=row, column=4, value=r["ticket"]).font = BODY_FONT
        ws.cell(row=row, column=5, value=r["summary"]).font = BODY_FONT
        hours = ws.cell(row=row, column=6, value=round(r["hours"], 4))
        hours.font = INPUT_FONT
        hours.number_format = HOURS_FMT
        for col in range(1, 7):
            ws.cell(row=row, column=col).border = BOX
        row += 1

    first, last = 4, row - 1
    total_row = row + 1
    ws.cell(row=total_row, column=5, value="TOTAL").font = BOLD_FONT
    total = ws.cell(row=total_row, column=6)
    total.value = f"=SUM(F{first}:F{last})" if last >= first else 0
    total.font = BOLD_FONT
    total.number_format = HOURS_FMT
    total.fill = SUBTOTAL_FILL
    ws.auto_filter.ref = f"A3:F{last}" if last >= first else None
    return ws, first, last


def _sheet_by_epic(wb, rows, first, last):
    ws = wb.create_sheet("By Engineer & Epic")
    ws["A1"] = "WBSO hours per engineer and epic"
    ws["A1"].font = TITLE_FONT
    ws["A2"] = "Every Hours cell is a SUMIFS over the Detail sheet."
    ws["A2"].font = NOTE_FONT
    _write_header(ws, 4, ["Engineer", "Epic key", "Epic", "Hours"], [24, 12, 40, 12])

    # De-duplicate (engineer, epic) pairs in Python — order is already sorted.
    pairs, seen = [], set()
    for r in rows:
        key = (r["engineer"], r["epic_key"], r["epic_label"])
        if key not in seen:
            seen.add(key)
            pairs.append(key)

    row = 5
    hours_col = f"Detail!$F${first}:$F${last}"
    eng_col = f"Detail!$A${first}:$A${last}"
    epic_col = f"Detail!$B${first}:$B${last}"

    for engineer, epic_key, epic_label in pairs:
        ws.cell(row=row, column=1, value=engineer).font = BODY_FONT
        ws.cell(row=row, column=2, value=epic_key).font = BODY_FONT
        ws.cell(row=row, column=3, value=epic_label).font = BODY_FONT
        cell = ws.cell(row=row, column=4)
        cell.value = f"=SUMIFS({hours_col},{eng_col},$A{row},{epic_col},$B{row})"
        cell.font = BODY_FONT
        cell.number_format = HOURS_FMT
        for col in range(1, 5):
            ws.cell(row=row, column=col).border = BOX
        row += 1

    total_row = row + 1
    ws.cell(row=total_row, column=3, value="TOTAL").font = BOLD_FONT
    total = ws.cell(row=total_row, column=4)
    total.value = f"=SUM(D5:D{row - 1})" if row > 5 else 0
    total.font = BOLD_FONT
    total.number_format = HOURS_FMT
    total.fill = SUBTOTAL_FILL
    return ws


def _sheet_summary(wb, rows, first, last, day_counts, busiest):
    ws = wb.create_sheet("Summary")
    ws["A1"] = "WBSO hours per engineer"
    ws["A1"].font = TITLE_FONT
    ws["A2"] = ("Hours are SUMIFS over Detail. Capacity = active days x hours-per-day "
                "(Assumptions!B5). Share = hours / capacity.")
    ws["A2"].font = NOTE_FONT
    _write_header(
        ws, 4,
        ["Engineer", "WBSO hours", "Day equivalent", "Active days",
         "Capacity hours", "WBSO share", "Peak tickets/day"],
        [24, 13, 15, 12, 15, 12, 17],
    )

    engineers, seen = [], set()
    for r in rows:
        if r["engineer"] not in seen:
            seen.add(r["engineer"])
            engineers.append(r["engineer"])

    hours_col = f"Detail!$F${first}:$F${last}"
    eng_col = f"Detail!$A${first}:$A${last}"

    row = 5
    for engineer in engineers:
        ws.cell(row=row, column=1, value=engineer).font = BODY_FONT

        hours = ws.cell(row=row, column=2)
        hours.value = f"=SUMIFS({hours_col},{eng_col},$A{row})"
        hours.number_format = HOURS_FMT

        day_equiv = ws.cell(row=row, column=3)
        day_equiv.value = f"=IFERROR($B{row}/{HOURS_PER_DAY_REF},0)"
        day_equiv.number_format = HOURS_FMT

        active = ws.cell(row=row, column=4, value=day_counts.get(engineer, 0))
        active.font = INPUT_FONT

        capacity = ws.cell(row=row, column=5)
        capacity.value = f"=$D{row}*{HOURS_PER_DAY_REF}"
        capacity.number_format = HOURS_FMT

        share = ws.cell(row=row, column=6)
        share.value = f"=IFERROR($B{row}/$E{row},0)"
        share.number_format = PCT_FMT

        peak, peak_day = busiest.get(engineer, (0, None))
        peak_text = f"{peak} on {peak_day:%d %b}" if peak_day else "-"
        ws.cell(row=row, column=7, value=peak_text).font = INPUT_FONT

        for col in range(1, 8):
            cell = ws.cell(row=row, column=col)
            cell.border = BOX
            if cell.font is None or cell.font.color is None:
                cell.font = BODY_FONT
        row += 1

    total_row = row + 1
    ws.cell(row=total_row, column=1, value="TEAM TOTAL").font = BOLD_FONT
    for col, formula in (
        (2, f"=SUM(B5:B{row - 1})"),
        (3, f"=SUM(C5:C{row - 1})"),
        (4, f"=SUM(D5:D{row - 1})"),
        (5, f"=SUM(E5:E{row - 1})"),
    ):
        cell = ws.cell(row=total_row, column=col, value=formula)
        cell.font = BOLD_FONT
        cell.number_format = HOURS_FMT
        cell.fill = SUBTOTAL_FILL
    share = ws.cell(row=total_row, column=6, value=f"=IFERROR($B{total_row}/$E{total_row},0)")
    share.font = BOLD_FONT
    share.number_format = PCT_FMT
    share.fill = SUBTOTAL_FILL
    return ws


def _sheet_diagnostics(wb, diagnostics):
    ws = wb.create_sheet("Diagnostics")
    ws["A1"] = "Mapping issues found during this run"
    ws["A1"].font = TITLE_FONT
    _write_header(ws, 3, ["Epic key", "Issue", "Example ticket", "Action"], [14, 40, 16, 52])

    row = 4
    for epic, ticket in sorted((diagnostics.get("unmapped_epics") or {}).items()):
        ws.cell(row=row, column=1, value=epic).font = BODY_FONT
        ws.cell(row=row, column=2, value="Absent from the mapping CSV entirely").font = BODY_FONT
        ws.cell(row=row, column=3, value=ticket).font = BODY_FONT
        ws.cell(row=row, column=4,
                value="Treated as non-WBSO. Add a row to the CSV if it should count.").font = BODY_FONT
        for col in range(1, 5):
            ws.cell(row=row, column=col).border = BOX
        row += 1

    for epic, ticket in sorted((diagnostics.get("wbso_other_team") or {}).items()):
        ws.cell(row=row, column=1, value=epic).font = BODY_FONT
        ws.cell(row=row, column=2, value="Flagged WBSO, but under another team's rows").font = BODY_FONT
        ws.cell(row=row, column=3, value=ticket).font = BODY_FONT
        ws.cell(row=row, column=4,
                value="Excluded. Re-run with --wbso-all-teams to include it.").font = BODY_FONT
        for col in range(1, 5):
            ws.cell(row=row, column=col).border = BOX
        row += 1

    if row == 4:
        cell = ws.cell(row=4, column=1, value="No mapping issues found.")
        cell.font = BODY_FONT
    return ws


def write_workbook(path, totals, summaries, day_counts, busiest, diagnostics, meta):
    """Build the workbook and return (path, detail_row_count)."""
    wb = Workbook()
    wb.remove(wb.active)

    epic_of = diagnostics.get("epic_of", {})
    rows = _flatten(totals, epic_of, summaries)

    _sheet_assumptions(wb, meta, diagnostics)
    _, first, last = _sheet_detail(wb, rows)
    _sheet_by_epic(wb, rows, first, last)
    _sheet_summary(wb, rows, first, last, day_counts, busiest)
    _sheet_diagnostics(wb, diagnostics)

    wb.save(path)
    return path, len(rows)
